# Dart CMD pipeline

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  #  - task: DartToolKit-FieldTrail@0
  #    inputs:
  #      sdkVersion: '2.4.0'
  #      preserveSDK: false
  #      buildSpec: 'dart --version; pub cache repair; pub get'

  - script: |
      sudo apt-get update
      sudo apt-get install apt-transport-https
      sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
      sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
      sudo apt-get update
      sudo apt-get install dart
      dart --version
    displayName: 'Dart Installation'

  - script: /usr/lib/dart/bin/pub get
    displayName: 'Resolve Dependencies'

  - script: dart main.dart
    displayName: 'Run main.dart'

  - script: /usr/lib/dart/bin/pub run test
    displayName: 'Run Tests'
