# Dart CMD pipeline

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DartToolKit-FieldTrail@0
    inputs:
      sdkVersion: '2.4.0'
      preserveSDK: false
      buildSpec: 'dart --version; pub cache repair; pub get'

  #  - script: dart main.dart
  #    displayName: 'Run main.dart'

  - script: ls /usr/lib/dart/bin/
    displayName: 'Dart ls'
